-- ==========================================
-- CINEMA BOOKING SYSTEM - PURE SQL
-- Dựa trên Django ORM Models
-- ==========================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Tạo django_content_type trước (auth_permission cần nó)
CREATE TABLE "django_content_type" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "app_label" varchar(100) NOT NULL, 
    "model" varchar(100) NOT NULL,
    UNIQUE ("app_label", "model")
);

-- Tạo auth_group và auth_permission (Django cần)
CREATE TABLE "auth_group" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "name" varchar(150) NOT NULL UNIQUE
);

CREATE TABLE "auth_permission" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "name" varchar(255) NOT NULL, 
    "content_type_id" integer NOT NULL, 
    "codename" varchar(100) NOT NULL,
    CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk" 
        FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") 
        DEFERRABLE INITIALLY DEFERRED
);

BEGIN;
--
-- Create model Auditorium
--
CREATE TABLE "api_auditorium" ("id" uuid NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), "name" varchar(60) NOT NULL UNIQUE, "standard_row_count" integer NOT NULL CHECK ("standard_row_count" >= 0), "vip_row_count" integer NOT NULL CHECK ("vip_row_count" >= 0), "couple_row_count" integer NOT NULL CHECK ("couple_row_count" >= 0), "seats_per_row" integer NOT NULL CHECK ("seats_per_row" >= 0), "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP);
--
-- Create model Genre
--
CREATE TABLE "api_genre" ("id" uuid NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), "name" varchar(60) NOT NULL UNIQUE);
--
-- Create model Movie
--
CREATE TABLE "api_movie" ("id" uuid NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), "title" varchar(200) NOT NULL, "duration_min" integer NOT NULL CHECK ("duration_min" >= 0), "rating" varchar(10) NULL, "release_date" date NULL, "description" text NOT NULL DEFAULT '', "poster_url" text NOT NULL DEFAULT '');
--
-- Create model User
--
CREATE TABLE "api_user" ("password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL DEFAULT FALSE, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL DEFAULT '', "last_name" varchar(150) NOT NULL DEFAULT '', "is_staff" boolean NOT NULL DEFAULT FALSE, "is_active" boolean NOT NULL DEFAULT TRUE, "date_joined" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, "id" uuid NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), "full_name" varchar(100) NULL, "email" varchar(254) NOT NULL UNIQUE, "phone" varchar(20) NULL, "role" varchar(12) NOT NULL DEFAULT 'user' CHECK ("role" IN ('user', 'admin')), "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, "date_of_birth" date NULL);
CREATE TABLE "api_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" uuid NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "api_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" uuid NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Seat
--
CREATE TABLE "api_seat" ("id" uuid NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), "row_label" varchar(5) NOT NULL, "seat_number" integer NOT NULL, "seat_type" varchar(10) NOT NULL DEFAULT 'standard' CHECK ("seat_type" IN ('standard', 'vip', 'couple')), "auditorium_id" uuid NOT NULL);
--
-- Create model Showtime
--
CREATE TABLE "api_showtime" ("id" uuid NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), "start_time" timestamp with time zone NOT NULL, "end_time" timestamp with time zone NOT NULL, "base_price" numeric(12, 2) NOT NULL DEFAULT 0, "status" varchar(20) NOT NULL DEFAULT 'scheduled', "auditorium_id" uuid NOT NULL, "movie_id" uuid NOT NULL);
--
-- Create model Booking
--
CREATE TABLE "api_booking" ("id" uuid NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), "status" varchar(20) NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending', 'reserved', 'paid', 'canceled')), "total_amount" numeric(12, 2) NOT NULL DEFAULT 0, "payment_method" varchar(30) NULL, "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, "expires_at" timestamp with time zone NULL, "user_id" uuid NOT NULL, "showtime_id" uuid NOT NULL);
--
-- Create model Ticket
--
CREATE TABLE "api_ticket" ("id" uuid NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), "price" numeric(12, 2) NOT NULL, "qr_code" varchar(64) NULL, "status" varchar(20) NOT NULL DEFAULT 'reserved' CHECK ("status" IN ('reserved', 'paid', 'checked_in', 'canceled', 'refunded')), "booked_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, "booking_id" uuid NOT NULL, "seat_id" uuid NOT NULL, "showtime_id" uuid NOT NULL);
--
-- Create model MovieGenre
--
CREATE TABLE "api_moviegenre" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "genre_id" uuid NOT NULL, "movie_id" uuid NOT NULL);
--
-- Create model Payment
--
CREATE TABLE "api_payment" ("id" uuid NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), "amount" numeric(12, 2) NOT NULL, "provider" varchar(40) NOT NULL DEFAULT 'credit_card' CHECK ("provider" IN ('credit_card', 'cash', 'e_wallet', 'bank_transfer')), "external_id" varchar(80) NULL, "status" varchar(20) NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending', 'completed', 'failed', 'refunded')), "paid_at" timestamp with time zone NULL, "created_at" timestamp with time zone NULL DEFAULT CURRENT_TIMESTAMP, "booking_id" uuid NOT NULL UNIQUE);
--
-- Create index api_showtim_movie_i_043b6b_idx on field(s) movie of model showtime
--
CREATE INDEX "api_showtim_movie_i_043b6b_idx" ON "api_showtime" ("movie_id");
--
-- Create index api_showtim_auditor_3717c2_idx on field(s) auditorium, start_time of model showtime
--
CREATE INDEX "api_showtim_auditor_3717c2_idx" ON "api_showtime" ("auditorium_id", "start_time");
--
-- Alter unique_together for showtime (1 constraint(s))
--
ALTER TABLE "api_showtime" ADD CONSTRAINT "api_showtime_auditorium_id_start_time_684efc01_uniq" UNIQUE ("auditorium_id", "start_time");
--
-- Create index api_booking_user_id_cfdf50_idx on field(s) user of model booking
--
CREATE INDEX "api_booking_user_id_cfdf50_idx" ON "api_booking" ("user_id");
--
-- Create index api_booking_showtim_c4c32e_idx on field(s) showtime of model booking
--
CREATE INDEX "api_booking_showtim_c4c32e_idx" ON "api_booking" ("showtime_id");
--
-- Create index api_booking_expires_651e73_idx on field(s) expires_at of model booking
--
CREATE INDEX "api_booking_expires_651e73_idx" ON "api_booking" ("expires_at");
--
-- Create index api_ticket_showtim_31e4c3_idx on field(s) showtime of model ticket
--
CREATE INDEX "api_ticket_showtim_31e4c3_idx" ON "api_ticket" ("showtime_id");
--
-- Alter unique_together for ticket (1 constraint(s))
--
ALTER TABLE "api_ticket" ADD CONSTRAINT "api_ticket_showtime_id_seat_id_c45a7e90_uniq" UNIQUE ("showtime_id", "seat_id");
CREATE INDEX "api_auditorium_name_af3b8bc3_like" ON "api_auditorium" ("name" varchar_pattern_ops);
CREATE INDEX "api_genre_name_321d7007_like" ON "api_genre" ("name" varchar_pattern_ops);
CREATE INDEX "api_user_username_cf4e88d2_like" ON "api_user" ("username" varchar_pattern_ops);
CREATE INDEX "api_user_email_9ef5afa6_like" ON "api_user" ("email" varchar_pattern_ops);
ALTER TABLE "api_user_groups" ADD CONSTRAINT "api_user_groups_user_id_group_id_9c7ddfb5_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "api_user_groups" ADD CONSTRAINT "api_user_groups_user_id_a5ff39fa_fk_api_user_id" FOREIGN KEY ("user_id") REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_user_groups" ADD CONSTRAINT "api_user_groups_group_id_3af85785_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_user_groups_user_id_a5ff39fa" ON "api_user_groups" ("user_id");
CREATE INDEX "api_user_groups_group_id_3af85785" ON "api_user_groups" ("group_id");
ALTER TABLE "api_user_user_permissions" ADD CONSTRAINT "api_user_user_permissions_user_id_permission_id_a06dd704_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "api_user_user_permissions" ADD CONSTRAINT "api_user_user_permissions_user_id_f3945d65_fk_api_user_id" FOREIGN KEY ("user_id") REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_user_user_permissions" ADD CONSTRAINT "api_user_user_permis_permission_id_305b7fea_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_user_user_permissions_user_id_f3945d65" ON "api_user_user_permissions" ("user_id");
CREATE INDEX "api_user_user_permissions_permission_id_305b7fea" ON "api_user_user_permissions" ("permission_id");
ALTER TABLE "api_seat" ADD CONSTRAINT "api_seat_auditorium_id_row_label_seat_number_c085b67f_uniq" UNIQUE ("auditorium_id", "row_label", "seat_number");
ALTER TABLE "api_seat" ADD CONSTRAINT "api_seat_auditorium_id_6213d2ec_fk_api_auditorium_id" FOREIGN KEY ("auditorium_id") REFERENCES "api_auditorium" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_seat_auditorium_id_6213d2ec" ON "api_seat" ("auditorium_id");
ALTER TABLE "api_showtime" ADD CONSTRAINT "api_showtime_auditorium_id_50f59683_fk_api_auditorium_id" FOREIGN KEY ("auditorium_id") REFERENCES "api_auditorium" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_showtime" ADD CONSTRAINT "api_showtime_movie_id_e8eff6d5_fk_api_movie_id" FOREIGN KEY ("movie_id") REFERENCES "api_movie" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_showtime_auditorium_id_50f59683" ON "api_showtime" ("auditorium_id");
CREATE INDEX "api_showtime_movie_id_e8eff6d5" ON "api_showtime" ("movie_id");
ALTER TABLE "api_booking" ADD CONSTRAINT "api_booking_user_id_0beb30da_fk_api_user_id" FOREIGN KEY ("user_id") REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_booking" ADD CONSTRAINT "api_booking_showtime_id_2b40e217_fk_api_showtime_id" FOREIGN KEY ("showtime_id") REFERENCES "api_showtime" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_booking_user_id_0beb30da" ON "api_booking" ("user_id");
CREATE INDEX "api_booking_showtime_id_2b40e217" ON "api_booking" ("showtime_id");
ALTER TABLE "api_ticket" ADD CONSTRAINT "api_ticket_booking_id_be136328_fk_api_booking_id" FOREIGN KEY ("booking_id") REFERENCES "api_booking" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_ticket" ADD CONSTRAINT "api_ticket_seat_id_a80d9c80_fk_api_seat_id" FOREIGN KEY ("seat_id") REFERENCES "api_seat" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_ticket" ADD CONSTRAINT "api_ticket_showtime_id_c02c9f36_fk_api_showtime_id" FOREIGN KEY ("showtime_id") REFERENCES "api_showtime" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_ticket_booking_id_be136328" ON "api_ticket" ("booking_id");
CREATE INDEX "api_ticket_seat_id_a80d9c80" ON "api_ticket" ("seat_id");
CREATE INDEX "api_ticket_showtime_id_c02c9f36" ON "api_ticket" ("showtime_id");
ALTER TABLE "api_moviegenre" ADD CONSTRAINT "api_moviegenre_movie_id_genre_id_76ce9461_uniq" UNIQUE ("movie_id", "genre_id");
ALTER TABLE "api_moviegenre" ADD CONSTRAINT "api_moviegenre_genre_id_e9ff3de3_fk_api_genre_id" FOREIGN KEY ("genre_id") REFERENCES "api_genre" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "api_moviegenre" ADD CONSTRAINT "api_moviegenre_movie_id_a4d5ccb0_fk_api_movie_id" FOREIGN KEY ("movie_id") REFERENCES "api_movie" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_moviegenre_genre_id_e9ff3de3" ON "api_moviegenre" ("genre_id");
CREATE INDEX "api_moviegenre_movie_id_a4d5ccb0" ON "api_moviegenre" ("movie_id");
ALTER TABLE "api_payment" ADD CONSTRAINT "api_payment_booking_id_cbb84fcd_fk_api_booking_id" FOREIGN KEY ("booking_id") REFERENCES "api_booking" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "api_payment_booking_a0e9be_idx" ON "api_payment" ("booking_id");
COMMIT;

-- ==========================================
-- PHẦN BỔ SUNG CHO BTL
-- ==========================================

-- TRIGGERS: Auto update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN 
    NEW.updated_at = CURRENT_TIMESTAMP; 
    RETURN NEW; 
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_auditorium_updated_at 
    BEFORE UPDATE ON api_auditorium 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_user_updated_at 
    BEFORE UPDATE ON api_user 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- TRIGGER: Set booking expiry (10 minutes)
CREATE OR REPLACE FUNCTION set_booking_expiry()
RETURNS TRIGGER AS $$
BEGIN 
    IF NEW.expires_at IS NULL THEN 
        NEW.expires_at = NEW.created_at + INTERVAL '10 minutes'; 
    END IF; 
    RETURN NEW; 
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_booking_expiry 
    BEFORE INSERT ON api_booking 
    FOR EACH ROW EXECUTE FUNCTION set_booking_expiry();

-- FUNCTION: Get available seats with calculated price
CREATE OR REPLACE FUNCTION get_available_seats(p_showtime_id UUID)
RETURNS TABLE (
    seat_id UUID, 
    row_label VARCHAR(5), 
    seat_number INTEGER, 
    seat_type VARCHAR(10), 
    calculated_price NUMERIC(12,2)
) AS $$
DECLARE 
    v_base_price NUMERIC(12,2);
BEGIN
    SELECT base_price INTO v_base_price FROM api_showtime WHERE id = p_showtime_id;
    
    RETURN QUERY
    SELECT 
        s.id, 
        s.row_label, 
        s.seat_number, 
        s.seat_type,
        v_base_price * CASE s.seat_type 
            WHEN 'standard' THEN 1.0 
            WHEN 'vip' THEN 1.5 
            WHEN 'couple' THEN 2.0 
        END
    FROM api_seat s
    WHERE s.auditorium_id = (SELECT auditorium_id FROM api_showtime WHERE id = p_showtime_id)
    AND NOT EXISTS (
        SELECT 1 FROM api_ticket t 
        WHERE t.seat_id = s.id 
        AND t.showtime_id = p_showtime_id 
        AND t.status IN ('reserved', 'paid', 'checked_in')
    )
    ORDER BY s.row_label, s.seat_number;
END;
$$ LANGUAGE plpgsql;

-- VIEW: Movies with their genres
CREATE OR REPLACE VIEW v_movie_with_genres AS
SELECT 
    m.id, 
    m.title, 
    m.duration_min, 
    m.rating, 
    m.release_date,
    m.description,
    m.poster_url,
    STRING_AGG(g.name, ', ' ORDER BY g.name) as genres
FROM api_movie m 
LEFT JOIN api_moviegenre mg ON m.id = mg.movie_id 
LEFT JOIN api_genre g ON mg.genre_id = g.id
GROUP BY m.id, m.title, m.duration_min, m.rating, m.release_date, m.description, m.poster_url;

-- SEED DATA: Insert initial genres
INSERT INTO api_genre (name) VALUES 
    ('Action'), 
    ('Comedy'), 
    ('Drama'), 
    ('Horror'), 
    ('Sci-Fi'), 
    ('Romance'), 
    ('Thriller'), 
    ('Animation')
ON CONFLICT (name) DO NOTHING;

-- Verify installation
SELECT 'Tables created' as status, COUNT(*) as count 
FROM information_schema.tables 
WHERE table_schema = 'public' AND table_name LIKE 'api_%';
